version: '3.8'

services:
  ar-io-node:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./.env:/app/.env
      - ./data:/app/data
    restart: unless-stopped
